/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRocketDialog: typeof import('./src/components/AddRocketDialog.vue')['default']
    ErrorState: typeof import('./src/components/ErrorState.vue')['default']
    LoadingState: typeof import('./src/components/LoadingState.vue')['default']
    RocketCard: typeof import('./src/components/RocketCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
